os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  
install:
  - sudo apt-get update
  - sudo apt-get install -y dpkg # fix https://github.com/travis-ci/travis-ci/issues/10132
  - sudo apt install -y xvfb  # required for opening nwjs during tests on the ci server

before_script:
  - ln -s $PWD ~/pynwjs && cd ~
  # download nwjs
  - mkdir -p ~/.nwjs
  - curl -s -o ~/.nwjs/nwjs.tar.gz https://dl.nwjs.io/v0.44.2/nwjs-v0.44.2-linux-x64.tar.gz
  - tar -xzf ~/.nwjs/nwjs.tar.gz --strip-components 1
  - export NWJS=~/.nwjs/nw

script:
  - cd ~/pynwjs
  # test package installation
  - sudo pip install -e ~/pynwjs  # required for pytest tests below
  - npm install ./pynwjs  # not required, but make sure that a failure is detected
  # run actual tests
  - xvfb-run pytest
